### ISSUE TITLE
Stingers Include - Server Freeze

### ISSUE THREAD

**Issue by TommyB123** [AbyssMorgan/SA-MP#10]
I haven't been able to pinpoint the exact cause or even reproduce the issue, but after successfully implementing your stingers include I've noticed that it can cause the SA-MP server to freeze up under an undiscovered set of conditions. I have not been able to successfully debug this issue or reproduce it, as stated. Players of my server have not been able to give me enough information unfortunately. If I'm able to find more info I'll let you know, but I figured it would be best to bring the issue to your attention regardless.

**Comment by AbyssMorgan** [comment]
Show me your #include

Did you add stinger near another stinger or you add player command for this ?

**Comment by TommyB123** [comment]
Here is the include file: https://pastebin.com/ByYShQLX
I modified it a little but I believe it's mostly the same still. I recall making it so the player who placed the stinger can also have their tires popped by it, but I doubt that would have any alarming effect.

This is also the code I use to create said stingers. There is not a check to see if two stingers are placed next to each other, however when testing to see if that was a cause the server did not freeze. I'll test again just to be sure.

```PAWN
CMD:stinger(cmdid, playerid, params[])
{
	if(!Logged{playerid}) return true;
	if(!IsCop(playerid)) return SysMsg(playerid, "You must be in the SASP to use this command.");
	if(GetPlayerVehicleID(playerid) > 0) return SysMsg(playerid, "You cannot deploy a stinger from within a vehicle.");
	for(new i = 0; i < MAX_STINGERS; i++) if(GetDynamicStingerPlayerID(i) == playerid) return SysMsg(playerid, "You have already placed a Stinger.");

	new Float:X, Float:Y, Float:Z, Float:Ang;
	GetPlayerPos(playerid, X, Y, Z);
	Ang = GetXYInFrontOfPlayer(playerid, X, Y, 5.0);
	CreateDynamicStinger(STINGER_TYPE_BIG, X, Y, Z - 1, 0.0, 0.0, Ang, GetPlayerVirtualWorld(playerid), GetPlayerInterior(playerid), -1, 300.0, ANY_TEAM, playerid);
	ProxDetector(20.0, playerid, sprintf("* Officer %s deploys a spike strip. *", NameRP(playerid)), COLOR_EMOTE);
	SendClientMessage(playerid, COLOR_BLUE, "Stinger Deployed! Use /rstinger to remove it.");
	return true;
}
```

**Comment by AbyssMorgan** [comment]
You need add this, if stinger is near another stinger can cause problems.
```
if(GetPlayerActiveDynamicStinger(playerid)) return SendClientMessage(playerid,-1,"You are near another stinger");
```

Also check full command added now:
http://forum.sa-mp.com/showthread.php?p=3874610#post3874610

**Comment by TommyB123** [comment]
I implemented `GetPlayerActiveDynamicStinger` and the freeze still happened. I threw together some debugs and it appears the server froze while executing this bit of code.

```PAWN
GetVehiclePartPos(STIN_LastVehicle[playerid],StingersPartTable[i],STIN_PlayerHCP[playerid][6],STIN_PlayerHCP[playerid][7],STIN_PlayerHCP[playerid][8]);
if(IsPointInCube3D(
	STIN_PlayerHCP[playerid][6],STIN_PlayerHCP[playerid][7],STIN_PlayerHCP[playerid][8],
	STIN_PlayerHCP[playerid][0],STIN_PlayerHCP[playerid][1],STIN_PlayerHCP[playerid][2],
	STIN_PlayerHCP[playerid][3],STIN_PlayerHCP[playerid][4],STIN_PlayerHCP[playerid][5],
	size_x,size_y,3.0
))
{
	TireStatus[i] = 1;
}
```
