### ISSUE TITLE
Script is stolen?

### ISSUE THREAD

**Issue by JustMe77** [AbyssMorgan/SA-MP#2]
Hey, I'm using your Include since a few weeks now I suddenly receive following Error

[ADM] Error: This script is stolen.

What's the problem?

**Comment by JustMe77** [comment]
Ok, I've found the problem.
It's because I am using Gammix's fixer.inc, any solution? I'd like to use both..

**Comment by AbyssMorgan** [comment]
Error List:
https://github.com/AbyssMorgan/SA-MP/blob/master/include/ADM%20Error%20List.txt

Files:
ScriptSecure.inc
MultiScriptSecure.inc

Error Name:
[ADM] Error: This script is stolen.

Error Description:
If the ip / port of the server is incorrect with the configuration script may be a problem.

Include Post:
http://forum.sa-mp.com/showthread.php?t=600408

Actions
1. Send me link for fixer.inc
2. Check you Script Secure configuration.

**Comment by JustMe77** [comment]
The IP & Port is fine.
Here is a link of the fixer include

http://forum.sa-mp.com/showthread.php?t=591458

**Comment by AbyssMorgan** [comment]
The problem may be the lack of a defined ip / port in server.cfg

Example:
server.cfg:
#bind 127.0.0.1
port 7778

bind is not defined

MultiScriptSecure Config:
//IP Port LicenseID MaxPlayers RconPassword Language
new ADMServerList[][e_server_config] = {
	{ "127.0.0.1", 7777, 20160201, 500, "123", "Polish" },
	{ "127.0.0.1", 7778, 20170201, 500, "123", "English" }
};

Server starts without given a bind, but the script finds that it is stolen.
I checked fixer.inc not a problem

**Comment by JustMe77** [comment]
No, it can't be a lack of a defined IP / Port or anything else, because it works fine if I uncomment the fixer.inc

**Comment by AbyssMorgan** [comment]
Insert this code debugging on top OnFilterScriptInit / OnGameModeInit and show log

new sid = FindServerID(), ADMserverIP[16], serverPort = GetServerVarAsInt("port");
GetServerVarAsString("bind",ADMserverIP,sizeof(ADMserverIP));
printf("[ADM DEBUG] Server ID: '%d' Bind: '%s' Port: '%d'",sid,ADMserverIP,serverPort);

for(new i = 0, j = sizeof(ADMServerList); i < j; i++){
	if(i == sid){
		printf("[ADM DEBUG] Record: %d Data: %s:%d L:%d P:%d L:%s [THIS SERVER]",i,ADMServerList[i][ADM_ADMserverIP],ADMServerList[i][ADM_ServerPort],ADMServerList[i][ADM_LicenseID],ADMServerList[i][ADM_MaxPlayers],ADMServerList[i][ADM_Language]);
	} else {
		printf("[ADM DEBUG] Record: %d Data: %s:%d LID:%d P:%d L:%s",i,ADMServerList[i][ADM_ADMserverIP],ADMServerList[i][ADM_ServerPort],ADMServerList[i][ADM_LicenseID],ADMServerList[i][ADM_MaxPlayers],ADMServerList[i][ADM_Language]);
	}
}

**Comment by JustMe77** [comment]
Do you mean inside the Include or my gamemode?

**Comment by JustMe77** [comment]
Anyways, if I put it inside the Include below OnFilterScriptInit, I receive this errors

C:\Users\David\Desktop\LnD\pawno\include\multisecure.inc(53) : error 017: undefined symbol "FindServerID"
C:\Users\David\Desktop\LnD\pawno\include\multisecure.inc(57) : error 017: undefined symbol "ADMServerList"
C:\Users\David\Desktop\LnD\pawno\include\multisecure.inc(57) : warning 215: expression has no effect
C:\Users\David\Desktop\LnD\pawno\include\multisecure.inc(57) : error 001: expected token: ")", but found ";"
C:\Users\David\Desktop\LnD\pawno\include\multisecure.inc(57) : error 036: empty statement
C:\Users\David\Desktop\LnD\pawno\include\multisecure.inc(57) : fatal error 107: too many error messages on one line

**Comment by AbyssMorgan** [comment]
I do not understand, if you use MultiScriptSecure.inc, why its function is not recognized.

**Comment by JustMe77** [comment]
I see I was actually using the normal secure thing (not multisecure)..

Could you add into the Multisecure File the features which the normal got?

#define FILE_LICENSEID			(20160830)		//<--- YYYYMMDD 01.02.2016 (DD.MM.YYYY) 

is for example not available in multisecure.inc and in my opinion that feature is very good..

**Comment by AbyssMorgan** [comment]
Error here:
[ADM DEBUG] Server ID: '-1' Bind: '' Port: '7777'
Edit server.cfg and add
bind 127.0.0.1

**Comment by JustMe77** [comment]
works now, thanks
