### ISSUE TITLE
Multiscript Secure - Feature

### ISSUE THREAD

**Issue by JustMe77** [AbyssMorgan/SA-MP#7]
I'd like to use it for Filterscripts and it's working well, but could you add an option what should happen when a Filterscript is "stolen" ?

I'd like just to unload the Filterscript if its not alright instead to close the server.
There should be an option to decide if the Script should be just unloaded or the whole server should be shut down.

**Comment by JustMe77** [comment]
Second suggestion:

I love the License ID feature (allowing script only for a certain date) but it's a bit annoying that you've to fill out also information like server ip etc. Could you make it that we dont have to fill out all informations, only the one which we like?

Something like this:

```
new ADMServerList[][e_server_config] = {
	{ "127.0.0.1", 7777, 500, "123", "Polish" },
	{ "127.0.0.1", 7778,500, "123", "English" }
};

new Scriptlicense[][e_server_config] = {
	{ "20170102" } 
};

```

I guess you know what i mean..
`

**Comment by AbyssMorgan** [comment]
I think it's time to expand this include.

For second question, i recommend this trick.
```
#define SERVER_LICENSEID	20170201

//IP Port LicenseID MaxPlayers RconPassword Language
new ADMServerList[][e_server_config] = {
	{ "127.0.0.1", 7777, SERVER_LICENSEID, 500, "123", "Polish" },
	{ "127.0.0.1", 7778, SERVER_LICENSEID, 500, "123", "English" }
};
```

**Comment by JustMe77** [comment]
I think you got my second suggestion wrong. I'll explain what I want to do:

I wanna share a FS from me without the sourcecode to a few people. I'll make the Filterscript only available for 30 days. But I dont want to fill out the server ip, port, max players, rcon pass and server language, I want an option to do without, understand?

 So the script would block the Filterscript if the 30 days are reached, which server ip they have etc doesn't matter..

**Comment by AbyssMorgan** [comment]
I go to create ultimate version for multi servers and option for enable/disable security options.
In addition, I will add the ability to add interaction with the activation of the protective.

**Comment by AbyssMorgan** [comment]
New version available:
http://forum.sa-mp.com/showpost.php?p=3838254&postcount=13
